/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/house_animations.glb -o components/models/house/One.tsx -r public --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'P2Action' | 'P3Action' | 'P5.001Action' | 'P5.003Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Plane012: THREE.Mesh
    Plane012_1: THREE.Mesh
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane022: THREE.Mesh
    Plane022_1: THREE.Mesh
    Plane023: THREE.Mesh
    Plane023_1: THREE.Mesh
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane006: THREE.Mesh
    Plane006_1: THREE.Mesh
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    Plane008: THREE.Mesh
    Plane008_1: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
    Plane018: THREE.Mesh
    Plane018_1: THREE.Mesh
    Plane020: THREE.Mesh
    Plane020_1: THREE.Mesh
    Plane021: THREE.Mesh
    Plane021_1: THREE.Mesh
    Root: THREE.Bone
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function HouseA(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/models/house_animations.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as any
  const { actions } = useAnimations(animations, group)

  // Activează toate animațiile la montarea componentei
  React.useEffect(() => {
    if (actions) {
      // Activează animațiile specifice după nume
      const animationNames: ActionName[] = ['P2Action', 'P3Action', 'P5.001Action', 'P5.003Action']

      animationNames.forEach((name) => {
        const action = actions[name]
        if (action) {
          action.play()
          // Opțional: configurează animația
          action.loop = THREE.LoopRepeat
          action.timeScale = 1.0 // Viteza animației
        }
      })
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null} scale={[0.3, .3, .3]} position={[0, 0, 0]} >
      <group name="Scene">
        <group name="Layer_1_curve_" />
        <group name="Crane_Rig" position={[-209.869, 31.598, 159.957]} rotation={[-0.187, 0.507, 0.092]}>
          <primitive object={nodes.Root} />
        </group>
        <group name="WGT-Camera_Root" />
        <group name="WGT-Camera" />
        <group name="WGT-Camera_Offset" />
        <group name="WGT-Aim" />
        <group name="P12" position={[-290.273, 38.401, 40.589]} rotation={[0.806, 0, 0]}>
          <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.Material} />
          <mesh name="Plane012_1" geometry={nodes.Plane012_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P14" position={[-264.669, 35.074, 25.589]} rotation={[Math.PI / 2, 0.69, -Math.PI / 2]}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Material} />
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P12001" position={[-290.273, 38.401, 10.254]} rotation={[2.336, 0, Math.PI]}>
          <mesh name="Plane022" geometry={nodes.Plane022.geometry} material={materials.Material} />
          <mesh name="Plane022_1" geometry={nodes.Plane022_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P14001" position={[-316.033, 34.926, 25.191]} rotation={[Math.PI / 2, -0.69, Math.PI / 2]}>
          <mesh name="Plane023" geometry={nodes.Plane023.geometry} material={materials.Material} />
          <mesh name="Plane023_1" geometry={nodes.Plane023_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P1" position={[-290.503, 0, 25.501]} scale={33.404}>
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.Material} />
          <mesh name="Plane001_1" geometry={nodes.Plane001_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P2" position={[-291.777, 54.399, -0.137]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.Material} />
          <mesh name="Plane002_1" geometry={nodes.Plane002_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P3" position={[-290.149, 55.858, 38.797]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.Material} />
          <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P6" position={[-290.946, 27.452, 25.375]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials.Material} />
          <mesh name="Plane006_1" geometry={nodes.Plane006_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P7" position={[-290.333, 33.743, 26.043]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials.Material} />
          <mesh name="Plane007_1" geometry={nodes.Plane007_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P8" position={[-256.052, 12.445, 45.86]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials.Material} />
          <mesh name="Plane008_1" geometry={nodes.Plane008_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P10" position={[-270.086, 12.907, 51.763]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials.Material} />
          <mesh name="Plane010_1" geometry={nodes.Plane010_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P5001" position={[-257.287, 82.8, -7.726]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
          <mesh name="Plane016" geometry={nodes.Plane016.geometry} material={materials.Material} />
          <mesh name="Plane016_1" geometry={nodes.Plane016_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P5003" position={[-323.753, 81.44, 46.37]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
          <mesh name="Plane018" geometry={nodes.Plane018.geometry} material={materials.Material} />
          <mesh name="Plane018_1" geometry={nodes.Plane018_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P8001" position={[-324.479, 12.445, 46.337]} rotation={[Math.PI, 0, Math.PI / 2]}>
          <mesh name="Plane020" geometry={nodes.Plane020.geometry} material={materials.Material} />
          <mesh name="Plane020_1" geometry={nodes.Plane020_1.geometry} material={materials['Material.002']} />
        </group>
        <group name="P10001" position={[-310.398, 12.907, 51.763]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="Plane021" geometry={nodes.Plane021.geometry} material={materials.Material} />
          <mesh name="Plane021_1" geometry={nodes.Plane021_1.geometry} material={materials['Material.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/house_animations.glb')
